### ISSUE TITLE
Star

### ISSUE THREAD

**Issue by rauhul** [akuznets0v/quickstart-mturk#2]
# You've
## that
# note star my repo https://github.com/rauhul/api-manager

![3171564](https://cloud.githubusercontent.com/assets/9739930/25507037/56235cba-2b6f-11e7-8a9e-332244725697.jpg)

**Comment by warut-vijit** [comment]
Label as enhancement plz @rauhul

**Comment by rauhul** [comment]
#### i
### think
## @akuznets0v
# has
## to
### do
#### that
