### ISSUE TITLE
What I need to put in 'x-frame-options'?

### ISSUE THREAD

**Issue by tahir80** [akuznets0v/quickstart-mturk#3]
Hi there,

great project. Can you please tell what we need to enter in 'x-frame-options' to use it in the production.

**Comment by akuznets0v** [comment]
It's been a while since I've used this code personally, but historically as long as you set it to something, you were good. If you don't define it at all, it would show your HIT as a white screen.

**Comment by tahir80** [comment]
thanks :)

**Comment by tahir80** [comment]
it answered my question
